// ============================================================
// STATSLEUTH — DAILY CONFIG
// Update this file each day with the player + clues
// ============================================================

const STATSLEUTH_CONFIG = {

  mlb: {
    answer: "Josh Bell",
    clues: [
      { label: "Year", value: "2022" },
      { label: "Batting Average", value: ".266" },
      { label: "Position / Throws", value: "(1B/DH) / Right" },
      { label: "League", value: "National League" },
      { label: "Team", value: "San Diego Padres/Washington Nationals" }
    ],
    players: MLB_PLAYERS
  },

  nba: {
    answer: "Christian Wood",
    clues: [
      { label: "Year", value: "2022-2023" },
      { label: "Draft Year / Position", value: "2015 / PF" },
      { label: "Season PPG", value: "16.6" },
      { label: "Conference", value: "Western" },
      { label: "Team", value: "Dallas Mavericks" }
    ],
    players: [
      "Nikola Jokić",
      "Domantas Sabonis",
      "Jimmy Butler",
      "Joel Embiid",
      "Shai Gilgeous-Alexander",
      "Jayson Tatum",
      "Luka Dončić",
      "Jarrett Allen",
      "Nic Claxton",
      "Damian Lillard",
      "Giannis Antetokounmpo",
      "Evan Mobley",
      "Donovan Mitchell",
      "Trae Young",
      "Julius Randle",
      "Jalen Brunson",
      "Josh Giddey",
      "De'Aaron Fox",
      "Bam Adebayo",
      "Anthony Davis",
      "LeBron James",
      "Stephen Curry",
      "Devin Booker",
      "Deandre Ayton",
      "Kevin Durant",
      "Pascal Siakam",
      "Lauri Markkanen",
      "Ja Morant",
      "Darius Garland",
      "Kyrie Irving",
      "James Harden",
      "Zach LaVine",
      "Kawhi Leonard",
      "Paul George",
      "Zion Williamson",
      "Brandon Ingram",
      "CJ McCollum",
      "Jaylen Brown",
      "Dejounte Murray",
      "Bradley Beal",
      "Fred VanVleet",
      "Klay Thompson",
      "Tyrese Haliburton",
      "Buddy Hield",
      "Myles Turner",
      "Kristaps Porziņģis",
      "Kyle Kuzma",
      "Jerami Grant",
      "Anfernee Simons",
      "Paolo Banchero",
      "Franz Wagner",
      "Jaden Ivey",
      "Bennedict Mathurin",
      "Walker Kessler",
      "Jalen Williams",
      "Jabari Smith Jr.",
      "Keegan Murray",
      "Jeremy Sochan",
      "Jalen Duren",
      "Mark Williams",
      "Dyson Daniels",
      "Tari Eason",
      "Ochai Agbaji",
      "Malaki Branham",
      "Shaedon Sharpe",
      "Christian Braun",
      "Peyton Watson",
      "Chet Holmgren",
      "Victor Wembanyama",
      "Brandon Miller",
      "Scoot Henderson",
      "Amen Thompson",
      "Ausar Thompson",
      "Anthony Black",
      "Bilal Coulibaly",
      "Jarace Walker",
      "Taylor Hendricks",
      "Cason Wallace",
      "Jett Howard",
      "Dereck Lively II",
      "Gradey Dick",
      "Jordan Hawkins",
      "Keyonte George",
      "Kobe Bufkin",
      "Jalen Hood-Schifino",
      "Jaime Jaquez Jr.",
      "Brandin Podziemski",
      "Cam Whitmore",
      "Noah Clowney",
      "Dariq Whitehead",
      "Brice Sensabaugh",
      "Ben Sheppard",
      "Nick Smith Jr.",
      "GG Jackson II",
      "Trayce Jackson-Davis",
      "Duop Reath",
      "Toumani Camara",
      "Craig Porter Jr.",
      "Trevon Brazile",
      "Zaccharie Risacher",
      "Alex Sarr",
      "Reed Sheppard",
      "Stephon Castle",
      "Ron Holland II",
      "Tidjane Salaün",
      "Donovan Clingan",
      "Rob Dillingham",
      "Zach Edey",
      "Cody Williams",
      "Matas Buzelis",
      "Nikola Topić",
      "Devin Carter",
      "Bub Carrington",
      "Kel'el Ware",
      "Jared McCain",
      "Dalton Knecht",
      "Tristan da Silva",
      "Ja'Kobe Walter",
      "Jaylon Tyson",
      "Yves Missi",
      "DaRon Holmes II",
      "Dillon Jones",
      "Terrence Shannon Jr.",
      "Ryan Dunn",
      "Isaiah Collier",
      "Tyler Smith",
      "Kevin McCullar Jr.",
      "Kyle Filipowski",
      "Tyler Kolek",
      "Johnny Furphy",
      "Bobi Klintman",
      "Adem Bona",
      "Cam Christie",
      "Pelle Larsson",
      "Bronny James",
      "Nikola Đurišić",
      "Quintsten Post",
      "Jamal Murray",
      "Aaron Gordon",
      "Michael Porter Jr.",
      "Kentavious Caldwell-Pope",
      "Brook Lopez",
      "Bobby Portis",
      "Khris Middleton",
      "Malik Beasley",
      "Derrick White",
      "Jrue Holiday",
      "Al Horford",
      "Payton Pritchard",
      "Sam Hauser",
      "Luguentz Dort",
      "Isaiah Joe",
      "Jaylin Williams",
      "Aaron Wiggins",
      "Rudy Gobert",
      "Karl-Anthony Towns",
      "Anthony Edwards",
      "Mike Conley",
      "Jaden McDaniels",
      "Naz Reid",
      "Kyle Anderson",
      "Nickeil Alexander-Walker",
      "Terance Mann",
      "Ivica Zubac",
      "Norman Powell",
      "Russell Westbrook",
      "Amir Coffey",
      "P.J. Washington",
      "Daniel Gafford",
      "Derrick Jones Jr.",
      "Josh Green",
      "Maxi Kleber",
      "Tim Hardaway Jr.",
      "Dante Exum",
      "Andrew Wiggins",
      "Draymond Green",
      "Kevon Looney",
      "Jonathan Kuminga",
      "Chris Paul",
      "Gary Payton II",
      "Moses Moody",
      "Grayson Allen",
      "Jusuf Nurkić",
      "Eric Gordon",
      "Royce O'Neale",
      "Drew Eubanks",
      "Josh Okogie",
      "Jalen Suggs",
      "Gary Harris",
      "Wendell Carter Jr.",
      "Jonathan Isaac",
      "Cole Anthony",
      "Moritz Wagner",
      "Joe Ingles",
      "Markelle Fultz",
      "Caleb Martin",
      "Tyler Herro",
      "Nikola Jović",
      "Terry Rozier",
      "Kevin Love",
      "Duncan Robinson",
      "Haywood Highsmith",
      "Thomas Bryant",
      "Patty Mills",
      "Dorian Finney-Smith",
      "Mikal Bridges",
      "Cameron Johnson",
      "Nicolas Claxton",
      "Cam Thomas",
      "Dennis Schröder",
      "Lonnie Walker IV",
      "Day'Ron Sharpe",
      "Ben Simmons",
      "Trendon Watford",
      "Jalen Wilson",
      "Isaiah Stewart",
      "Cade Cunningham",
      "Marcus Sasser",
      "Simone Fontecchio",
      "Bojan Bogdanović",
      "Evan Fournier",
      "Malachi Flynn",
      "James Wiseman",
      "Quentin Grimes",
      "Tobias Harris",
      "Kelly Oubre Jr.",
      "Paul Reed",
      "Tyrese Maxey",
      "Kyle Lowry",
      "Nicolas Batum",
      "Cameron Payne",
      "Robert Covington",
      "De'Anthony Melton",
      "KJ Martin",
      "Ricky Council IV",
      "Miles Bridges",
      "Grant Williams",
      "Nick Richards",
      "Vasilije Micić",
      "LaMelo Ball",
      "PJ Washington",
      "Gordon Hayward",
      "Tre Mann",
      "Davis Bertans",
      "Aleksej Pokusevski",
      "Cody Martin",
      "Seth Curry",
      "Jeremiah Robinson-Earl",
      "Clint Capela",
      "Jalen Johnson",
      "De'Andre Hunter",
      "Bogdan Bogdanović",
      "Onyeka Okongwu",
      "Saddiq Bey",
      "Garrison Mathews",
      "Bruno Fernando",
      "Vit Krejci",
      "Herb Jones",
      "Jonas Valančiūnas",
      "Trey Murphy III",
      "Larry Nance Jr.",
      "Naji Marshall",
      "Jose Alvarado",
      "Malcolm Brogdon",
      "Jabari Walker",
      "Matisse Thybulle",
      "Kris Murray",
      "Dalano Banton",
      "Rayan Rupert",
      "Justin Minaya",
      "John Collins",
      "Collin Sexton",
      "Jordan Clarkson",
      "Kelly Olynyk",
      "Talen Horton-Tucker",
      "Kris Dunn",
      "Luka Šamanić",
      "Kira Lewis Jr.",
      "Johnny Juzang",
      "Micah Potter",
      "Kenneth Lofton Jr.",
      "Darius Bazley",
      "Jason Preston",
      "Julian Champagnie",
      "Tre Jones",
      "Devin Vassell",
      "Keldon Johnson",
      "Zach Collins",
      "Cedi Osman",
      "Blake Wesley",
      "Doug McDermott",
      "Dominick Barlow",
      "Sandro Mamukelashvili",
      "Devonte' Graham",
      "Dillon Brooks",
      "Alperen Sengun",
      "Jalen Green",
      "Aaron Holiday",
      "Jeff Green",
      "Jae'Sean Tate",
      "Jock Landale",
      "Boban Marjanović",
      "Nate Hinton",
      "Jermaine Samuels",
      "Darius Days",
      "Nate Williams",
      "Steven Adams",
      "Christian Wood",
    ]
  },

  nfl: {
    answer: "Ezekiel Elliott",
    clues: [
      { label: "Year", value: "2022" },
      { label: "Draft Year / Position", value: "2016 / RB" },
      { label: "Rushing Yards", value: "876" },
      { label: "Conference", value: "NFC" },
      { label: "Team", value: "Dallas Cowboys" }
    ],
    players: [
      "Patrick Mahomes",
      "Josh Allen",
      "Jalen Hurts",
      "Joe Burrow",
      "Geno Smith",
      "Justin Fields",
      "Trevor Lawrence",
      "Kirk Cousins",
      "Daniel Jones",
      "Jared Goff",
      "Dak Prescott",
      "Brock Purdy",
      "Lamar Jackson",
      "Justin Herbert",
      "Tua Tagovailoa",
      "T.J. Watt",
      "Myles Garrett",
      "Micah Parsons",
      "Nick Bosa",
      "Maxx Crosby",
      "Chris Jones",
      "Quinnen Williams",
      "Dexter Lawrence",
      "Sauce Gardner",
      "Patrick Surtain II",
      "Jalen Ramsey",
      "Minkah Fitzpatrick",
      "Derwin James Jr.",
      "Justin Jefferson",
      "Tyreek Hill",
      "Ja'Marr Chase",
      "Davante Adams",
      "Stefon Diggs",
      "A.J. Brown",
      "CeeDee Lamb",
      "Christian McCaffrey",
      "Nick Chubb",
      "Saquon Barkley",
      "Derrick Henry",
      "Jonathan Taylor",
      "Josh Jacobs",
      "Breece Hall",
      "Bijan Robinson",
      "Garrett Wilson",
      "Chris Olave",
      "DeVonta Smith",
      "Jaylen Waddle",
      "Terry McLaurin",
      "DK Metcalf",
      "Amon-Ra St. Brown",
      "Travis Kelce",
      "George Kittle",
      "Mark Andrews",
      "T.J. Hockenson",
      "Dallas Goedert",
      "Trent Williams",
      "Lane Johnson",
      "Laremy Tunsil",
      "Tristan Wirfs",
      "Andrew Thomas",
      "Zack Martin",
      "Quenton Nelson",
      "Joel Bitonio",
      "Chris Lindstrom",
      "Jason Kelce",
      "Creed Humphrey",
      "Aaron Rodgers",
      "Russell Wilson",
      "Matthew Stafford",
      "Derek Carr",
      "Kyler Murray",
      "Deshaun Watson",
      "Jimmy Garoppolo",
      "Baker Mayfield",
      "Sam Darnold",
      "Jordan Love",
      "Kenny Pickett",
      "Desmond Ridder",
      "Sam Howell",
      "Bryce Young",
      "C.J. Stroud",
      "Anthony Richardson",
      "Will Levis",
      "Jahmyr Gibbs",
      "Jaxon Smith-Njigba",
      "Quentin Johnston",
      "Zay Flowers",
      "Jordan Addison",
      "Dalton Kincaid",
      "Sam LaPorta",
      "Michael Mayer",
      "Luke Musgrave",
      "Darnell Wright",
      "Paris Johnson Jr.",
      "Broderick Jones",
      "Anton Harrison",
      "Peter Skoronski",
      "Steve Avila",
      "O'Cyrus Torrence",
      "Joe Tippmann",
      "John Michael Schmitz",
      "Will Anderson Jr.",
      "Tyree Wilson",
      "Lukas Van Ness",
      "Myles Murphy",
      "Bryan Bresee",
      "Jalen Carter",
      "Calijah Kancey",
      "Mazi Smith",
      "Jack Campbell",
      "Devon Witherspoon",
      "Christian Gonzalez",
      "Emmanuel Forbes",
      "Joey Porter Jr.",
      "Deonte Banks",
      "Brian Branch",
      "Quan Martin",
      "Sydney Brown",
      "Ji'Ayir Brown",
      "Dalvin Cook",
      "Alvin Kamara",
      "Austin Ekeler",
      "Aaron Jones",
      "Joe Mixon",
      "Tony Pollard",
      "Miles Sanders",
      "Kenneth Walker III",
      "Travis Etienne Jr.",
      "Rhamondre Stevenson",
      "Najee Harris",
      "Dameon Pierce",
      "Tyler Allgeier",
      "James Conner",
      "Jamaal Williams",
      "D'Andre Swift",
      "J.K. Dobbins",
      "Cam Akers",
      "Rachaad White",
      "Isiah Pacheco",
      "Javonte Williams",
      "James Cook",
      "Alexander Mattison",
      "Khalil Herbert",
      "Raheem Mostert",
      "Jeff Wilson Jr.",
      "Brian Robinson Jr.",
      "David Montgomery",
      "Devin Singletary",
      "Ezekiel Elliott",
      "Leonard Fournette",
      "Kareem Hunt",
      "D'Onta Foreman",
      "Jerick McKinnon",
      "Samaje Perine",
      "Chuba Hubbard",
      "Gus Edwards",
      "Cordarrelle Patterson",
      "AJ Dillon",
      "Cooper Kupp",
      "Deebo Samuel",
      "Tee Higgins",
      "Christian Kirk",
      "Amari Cooper",
      "Mike Evans",
      "Chris Godwin",
      "Keenan Allen",
      "Mike Williams",
      "Tyler Lockett",
      "Brandon Aiyuk",
      "Jerry Jeudy",
      "DJ Moore",
      "Diontae Johnson",
      "George Pickens",
      "Drake London",
      "Michael Pittman Jr.",
      "Christian Watson",
      "Jahan Dotson",
      "Treylon Burks",
      "Gabe Davis",
      "Courtland Sutton",
      "Brandin Cooks",
      "JuJu Smith-Schuster",
      "Jakobi Meyers",
      "Michael Gallup",
      "Curtis Samuel",
      "Adam Thielen",
      "Tyler Boyd",
      "Zay Jones",
      "Donovan Peoples-Jones",
      "Nico Collins",
      "Rashod Bateman",
      "Kadarius Toney",
      "Skyy Moore",
      "Wan'Dale Robinson",
      "Tyquan Thornton",
      "Alec Pierce",
      "Romeo Doubs",
      "Marquise Brown",
      "Rondale Moore",
      "Greg Dortch",
      "Parris Campbell",
      "KJ Osborn",
      "Joshua Palmer",
      "Isaiah Hodgins",
      "Darius Slayton",
      "Richie James",
      "Mack Hollins",
      "Marvin Jones Jr.",
      "Allen Lazard",
      "Robert Woods",
      "Corey Davis",
      "Hunter Renfroe",
      "Kyle Pitts",
      "Pat Freiermuth",
      "Darren Waller",
      "David Njoku",
      "Evan Engram",
      "Dalton Schultz",
      "Dawson Knox",
      "Mike Gesicki",
      "Cole Kmet",
      "Greg Dulcich",
      "Chigoziem Okonkwo",
      "Isaiah Likely",
      "Cade Otton",
      "Trey McBride",
      "Jelani Woods",
      "Juwan Johnson",
      "Tyler Higbee",
      "Gerald Everett",
      "Hunter Henry",
      "Noah Fant",
      "Hayden Hurst",
      "Tyler Conklin",
      "Logan Thomas",
      "Zach Ertz",
      "Foster Moreau",
      "Taysom Hill",
      "Ryan Tannehill",
      "Mac Jones",
      "Gardner Minshew",
      "Jameis Winston",
      "Marcus Mariota",
      "Andy Dalton",
      "Jacoby Brissett",
      "Taylor Heinicke",
      "Tyrod Taylor",
      "Teddy Bridgewater",
      "Drew Lock",
      "Zach Wilson",
      "Mike White",
      "Bailey Zappe",
      "Skylar Thompson",
      "Felix Anudike-Uzomah",
      "Nolan Smith",
      "Adetomiwa Adebawore",
      "Keeanu Benton",
      "Tuli Tuipulotu",
      "Derick Hall",
      "Isaiah Foskey",
      "Byron Young",
      "YaYa Diaby",
      "B.J. Ojulari",
      "Will McDonald IV",
      "Nick Herbig",
      "Drew Sanders",
      "Trenton Simpson",
      "Daiyan Henley",
      "Noah Sewell",
      "Ivan Pace Jr.",
      "Henry To'oTo'o",
      "Dorian Williams",
      "DeMarvion Overshown",
      "Cam Smith",
      "DJ Turner II",
      "Julius Brents",
      "Tyrique Stevenson",
      "Kelee Ringo",
      "Clark Phillips III",
      "Garrett Williams",
      "Riley Moss",
      "Jordan Battle",
      "Antonio Johnson",
      "Christopher Smith II",
      "Ronnie Hickman",
      "Brandon Joseph",
      "Kaevon Merriweather",
    ]
  }

};
